import type { Metadata } from "next";
import { Inter} from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";
const inter = Inter({
  subsets: ['latin'],
  preload: true,
  weight: ["400", "500", "600", "700", "800", "900"]
})
export const metadata: Metadata = {
  title: "Sass website",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body content="width=device-width, initial-scale=1.0"
        className={`${inter.className} antialiased bg-white`}
      >
        <main className="w-full">
        </main>
          <Navbar/>
          {children}
      </body>
    </html>
  );
}
